return {
	-- LSP LEFT TO MOVE
	-- SEE https://github.com/neovim/nvim-lspconfig/tree/master/lsp

	-- lspconfig.bashls.setup(default_config)
	-- lspconfig.clangd.setup(default_config)
	-- lspconfig.cssls.setup(default_config)
	-- lspconfig.jsonls.setup(default_config)
	-- lspconfig.pylsp.setup(default_config)
	-- lspconfig.ts_ls.setup(default_config)
	-- lspconfig.lua_ls.setup({
	-- 	on_attach = on_attach,
	-- 	capabilities = capabilities,
	-- 	settings = {
	-- 		Lua = {
	-- 			diagnostics = { globals = { "vim", "require", "hs", "spoon" } },
	-- 		},
	-- 		workspace = {
	-- 			-- Make the server aware of Neovim runtime files
	-- 			library = vim.api.nvim_get_runtime_file("", true),
	-- 		},
	-- 		telemetry = { enable = false },
	-- 	},
	-- })
	--
	-- lspconfig.gdscript.setup({
	-- 	on_attach = on_attach,
	-- 	capabilities = capabilities,
	-- 	flags = { debounce_text_changes = 150 },
	-- })
	--
	-- end,
}
