#!/usr/bin/env zsh

# Install manually
open https://github.com/kovidgoyal/kitty/releases

# Add "include other conf" in default conf file
mkdir -p ~/.config/kitty/
cat << EOF > ~/.config/kitty/kitty.conf
#press gf on here
include $DOTFILE_FOLDER/kitty/kitty.conf
EOF
