#!/bin/sh
set -e

# Build a tags file inside the .git directory, will be used on hooks
# Inspired by https://github.com/tpope/tpope/blob/master/.git_template/hooks/ctags

git_dir="`git rev-parse --git-dir`"

trap 'rm -f "$git_dir/tags.$$"' EXIT INT TERM

ctags --tag-relative=yes -f$git_dir/tags.$$ $(git ls-files)

mv $git_dir/tags.$$ $git_dir/tags
