#!/usr/bin/env bash

set -e

default_branch="$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
current_branch="$(git rev-parse --abbrev-ref HEAD)"
git stash
git checkout "$default_branch"
git branch -D "$current_branch"
git checkout -b "$current_branch"
