#!/usr/bin/env zsh

list_file=${DOTFILE_FOLDER}/.link-list
[ ! -f "$list_file" ] && echo "OPEN_LIST" > "$list_file"

sane_list="$(cat $list_file | sed '/^#/d; /^$/d')"

choice="$(echo $sane_list | fzf)"
if [ -z "$choice" ]; then
	echo "No choice, aborting."
	return 1
fi

if [ "$choice" = "OPEN_LIST" ]; then
	echo "Opening $list_file in $EDITOR."
	$EDITOR "$list_file"
	return 0
fi

url="$(echo $choice | cut -d' ' -f1)"
if [ -z "$url" ]; then
	echo "No url, aborting."
	return 1
fi

echo "Copying '$url' in the clipboard."
printf "$url" | pbcopy
