#!/usr/bin/env bash

local command
command="${1:-}"
if [ "$#" -gt 0 ]; then
	shift
fi

case "$command" in
rehash|shell)
	eval "$(nodenv "sh-$command" "$@")";;
*)
	command nodenv "$command" "$@";;
esac
