#!/usr/bin/env bash

source "$DOTFILE_FOLDER/utils.zsh"

is_macos && {
	command="display notification \"$1\" with title \"notify\""
	osascript -e "$command"
}

is_linux && {
	notify-send "$1" -t 1000
}
