#!/usr/bin/env bash

local prompt="%{$fg[green]%}%c%{$fg[red]%}"

branch="$((git symbolic-ref -q HEAD --short || git name-rev --name-only --no-undefined --always HEAD) 2> /dev/null | xargs)"
if [ -n "$branch" ]; then
  local dirty=""
  if (! git diff-index --quiet HEAD -- 2> /dev/null); then
    dirty="*"
  fi

  local stash=`expr $(git stash list 2> /dev/null | wc -l)`
  if [ "$stash" = "0" ]; then
    stash=""
  fi

  prompt="$prompt$branch$stash$dirty"
fi

[ -n "$VIRTUAL_ENV" ] && prompt="$prompt%{$fg[blue]%}$(basename $VIRTUAL_ENV)"

echo "$prompt%{$reset_color%} "
