#!/usr/bin/env bash

# shellcheck disable=2154
# Colors are defined.

# shellcheck disable=1087
prompt="%{$fg[green]%}%c%{$fg[red]%}"

branch="$( (git symbolic-ref -q HEAD --short || git name-rev --name-only --no-undefined --always HEAD) 2> /dev/null | xargs)"
if [ -n "$branch" ]; then

  stash_count="$(git stash list 2> /dev/null | wc -l | tr -d ' ')"
  [ "${stash_count}" = "0" ] && stash_count=""

  git update-index --refresh >/dev/null
  if ! git diff-index --no-ext-diff --quiet --exit-code HEAD --; then
    dirty="*"
  fi

  prompt="${prompt}${branch}${stash_count}${dirty}"
fi

[ -n "$VIRTUAL_ENV" ] && prompt="${prompt}%{$fg[blue]%}$(basename "${VIRTUAL_ENV}")"

echo "$prompt%{$reset_color%} "
