#!/usr/bin/env bash

set -e

# Select the aws profile
profile="$(cat ~/.aws/credentials | grep '\[' | sed 's/^\[\(.*\)]$/\1/' | fzf --select-1)"
if [ -z "$profile" ]; then
	echo "No profile, aborting."
	return 1
fi

# Fetch the aws hosted zones
echo "Fetching the hosted zones, hold on..."
hosted_zones="$(aws --cli-connect-timeout 1 --profile $profile route53 list-hosted-zones | jq '.HostedZones[].Id' | sed 's/\"//g' )"
if [ -z "$hosted_zones" ]; then
	echo "No hosted zones, aborting."
	return 1
fi

# Fetch and concatednate the aws routes from the hosted zones
echo "Fetching the routes, hold on..."
routes=""
echo "$hosted_zones" | while read zone; do
	routes="$(aws --cli-connect-timeout 1 --profile "$profile" route53 list-resource-record-sets --hosted-zone-id $zone | jq '.ResourceRecordSets | .[].Name' | sed -e 's/\"//g' -e 's/.$//')\n$routes"
done

# Cleaning up the empty lines and removing dupplicates
routes="$(echo "$routes" | sed '/^$/d' | sort -u)"

if [ -z "$routes" ]; then
	echo "No routes, aborting."
	return 1
fi

# Select the route we want
route="$(echo "$routes" | fzf --select-1 --exit-0)"

echo "Copying '$route' into the clipboard."
printf "%s" "$route" | pbcopy

