#!/usr/bin/env zsh

bot_id="bot$(cat $DOTFILE_FOLDER/.telegram-creds | head -n1)"
channel_id="$(cat $DOTFILE_FOLDER/.telegram-creds | tail -n1)"

curl -q -s \
	-X POST \
	"https://api.telegram.org/$bot_id/sendMessage" \
	-d chat_id="$channel_id" \
	-d text="$*"
