#!/usr/bin/env bash

curl 'https://www.ups.com/track/api/Track/GetStatus?loc=en_US' \
	-s \
	-H 'Accept: application/json, text/plain, */*' \
	--compressed \
	-H 'Content-Type: application/json' \
	--data-raw '{"Locale":"en_US","TrackingNumber":["'$1'"]}' \
	| jq '.trackDetails[0].shipmentProgressActivities
	| reverse
	| .[]
	| select(.activityScan != null)
	| .date + " " + .time + " - " + .location + " - " + .activityScan'
