#!/usr/bin/env bash
#/ x: search for an executable and run it

set -e

command=$(
	find . \
		-type f \
		\( -perm -u=x -o -perm -g=x -o -perm -o=x \) \
		-not -path './vendor/*' \
		-not -path './.git/*' \
		| fzf --select-1
)

"$command" || true

print -s "$command"
