tap "homebrew/services"
tap "1password/tap"

brew "cmake"
brew "age"
brew "difftastic"
brew "fd"
brew "fzf"
brew "gh"
brew "glow"
brew "gnupg"
brew "gnupg2"
brew "go"
brew "gojq"
brew "htop"
brew "moreutils"
brew "neovim"
brew "pinentry-mac"
brew "ripgrep"
brew "tealdeer"
brew "trash"
brew "tree"
brew "universal-ctags"
brew "xq"

brew "mise"
brew "pipenv"
brew "pyenv"
brew "rbenv"
brew "nodenv"

cask_args appdir: "~/Applications", require_sha: true

cask "1password" , args: { appdir: "/Applications" }
cask "1password-cli"
cask "docker-desktop"
cask "hammerspoon"
cask "kitty"
cask "neovide-app"
cask "notunes"
