# Use `espanso edit` to auto-reload after change.
# Alternatively, vim will do `espanso restart` after this file is modified.

auto_restart: true
show_icon: false
show_notifications: false

matches:
  - triggers: ["comitted", "comited", "commited"]
    replace: "committed"

  - trigger: ";1-1"
    replace: |-
      # {{now}}
      ## Awareness/Visibility
        Anything that needs to be on management's radar

      ## Challenges/Blockers
        Anything you need management assistance with

      ## Accomplishments
        Toot your own horn :-)

      ## Administrative
        Any HR, performance, organization related questions

    vars:
      - name: now
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ";date"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%d/%m/%Y"

  - triggers: [";et", ";ent", ";ettt"]
    replace: "entitlements"
    word: true

  - triggers: [";ets", ";ents", ";status", ";stt"]
    replace: ".entitlements status"
    word: true

  - triggers: [";ettd", ";et train deploy"]
    replace: ".entitlements entrain --deploy"
    word: true

  - trigger: ";chrq"
    replace: "I'm adding the `Changes Requested` label. Feel free to remove it once you're done with your changes."
    word: true

  - trigger: ";aptr"
    replace: "The PR has been approved and will be deployed in the next train :)"
    word: true
