# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: nvim
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: >
    nvim -R -c "execute 'write! ' . system('mktemp')" -c "term cat %" -c "set nolist" -

aliases:
    co: pr checkout
    chk: "gh pr checks"
    chks: "!while true; do gh pr checks; sleep 1; done"
    err: '!gh pr view --comments | grep ''FATAL\|Errno'''
    et: "!~/.dot/private_functions/gh-pr-repl-ettt"
    merge-pr-delete-branch: pr merge --merge --delete-branch
    comments-pr-full: pr view --comments
    clone: repo clone
    open: repo view --web
    limits: '!github-limits'
