#!/usr/bin/env zsh

if [ -n "$IS_MACOS" ]; then
	brew install ripgrep
	brew install fzf
	$(brew --prefix)/opt/fzf/install --bin
fi

if [ -n "$IS_LINUX" ]; then
	curl -L https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb -o ./search/ripgrep.deb
	sudo dpkg -i ./search/ripgrep.deb
	rm ./search/ripgrep.deb
	sudo apt-get install fzf
fi
