#!/usr/bin/env zsh

# Install Vim
# Install it manually and the vim.zsh will make sure it's linked correctly
if [ -n "$IS_MACOS" ]; then
	open https://github.com/macvim-dev/macvim/releases
fi

if [ -n "$IS_LINUX" ]; then
	echo "open https://github.com/macvim-dev/macvim/releases"
fi

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Add the swapfile and undodir folder
mkdir -p ~/.vim/swapdir/
mkdir -p ~/.vim/undodir/
