# Use `espanso edit` to auto-reload after change.
# Alternatively, vim will do `espanso restart` after this file is modified.

auto_restart: true
show_icon: false
show_notifications: false

matches:
  - trigger: ";date"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%d/%m/%Y"

  - triggers: [";et", ";ent", ";ettt"]
    replace: "entitlements"
    word: true

  - triggers: [";ets", ";ents"]
    replace: ".entitlements status"
    word: true

  - triggers: [";ettd", ";et train deploy"]
    replace: ".entitlements entrain --deploy"
    word: true
