$font = CommitMonoV143
$f-big = 400
$f-normal = 100
$fg = rgb(cecdc3) # c8
$bg = rgb(1d1f21) # c1
$check = rgb(3971ed) # c5
$fail = rgb(cc342b) # c2

general {
	hide_cursor = true
	ignore_empty_input = true
}

animations {
	enabled = false
}

background {
	color = $bg
}

# TIME
label {
	font_family = $font
	font_size = $f-big
	text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
	color = $fg

	position = 0, 0
}

# DATE
label {
	font_family = $font
	font_size = $f-normal
	text = cmd[update:60000] date +"%F"
	color = $fg

	position = 0, $f-big
}

# WEATHER
label {
	font_family = $font
	font_size = $f-normal
	text = cmd[update:60000] /home/nobe4/dev/nobe4/dotfiles/bin/weather --simple
	color = $fg

	position = 0, -$f-big
}

input-field {
	zindex = 1
	size = 100%, 20%

	outline_thickness = 0
	rounding = 0

	inner_color = $bg
	outer_color = $fg
	font_color = $fg
	check_color = $check
	fail_color = $fail

	font_family = $font
	placeholder_text =

	fail_text = $PAMFAIL

	dots_text_format = X
}

