#!/usr/bin/env zsh

curl -L https://github.com/adobe-fonts/source-code-pro/archive/refs/heads/release.zip -o /tmp/source-code-pro.zip
unzip -q /tmp/source-code-pro.zip -d /tmp/

if [ -n "$IS_MACOS" ]; then
	mv /tmp/source-code-pro-release/TTF/* /Library/Fonts/
fi

if [ -n "$IS_LINUX" ]; then
	mv /tmp/source-code-pro-release/TTF/* /usr/local/share/fonts/
fi
