#!/usr/bin/env zsh

if [ -n "$IS_MACOS" ]; then
	curl -o /Library/Fonts/Hack-Regular.ttf https://raw.githubusercontent.com/chrissimpkins/Hack/master/build/ttf/Hack-Regular.ttf
fi

if [ -n "$IS_LINUX" ]; then
	sudo curl -o /usr/local/share/fonts/Hack-Regular.ttf https://raw.githubusercontent.com/chrissimpkins/Hack/master/build/ttf/Hack-Regular.ttf
fi
