#!/usr/bin/env zsh

if [ -n "$IS_MACOS" ]; then
	open https://golang.org/doc/install
fi

if [ -n "$IS_LINUX" ]; then
	# https://github.com/golang/go/wiki/Ubuntu
	sudo add-apt-repository ppa:longsleep/golang-backports
	sudo apt update
	sudo apt install golang-go
fi

go get golang.org/x/tools/cmd/goimports
