#!/usr/bin/env bash
#/ Usage: deploy PR
#/
#/ Sends the PR to deploy on slack.
#/ If one or multiple URLs are in your clipboard, it will propose to default to
#/ that.
#/
#/ Requirements:
#/  - pbpaste
#/  - gh - https://cli.github.com/
#/  - gh-slack - https://github.com/rneatherway/gh-slack

set -e

TEAM="$(cat "${DOTFILE_FOLDER}/private/launch/slack_team")"
CHANNEL="$(cat "${DOTFILE_FOLDER}/private/launch/deploy_channel")"

default="$(pbpaste | grep 'https://github.com/.\+/pull/\d\+' || true)"

echo "Enter a URL to deploy in ${TEAM}/#${CHANNEL}"
if [[ "${default}" != "" ]]; then
  echo "or <CR> to use: '${default}'"
fi

printf '> '
read -r input

echo "${input:-${default}}" | while IFS= read -r line; do
  message=".deploy ${line}"

  echo -e "Sending '${message}'\n\tto ${TEAM}/#${CHANNEL}"
  gh slack send \
    --team "${TEAM}" \
    --channel "${CHANNEL}" \
    --message "${message}"
  sleep 1
done
