# Use `espanso edit` to auto-reload after change.
# Alternatively, vim will do `espanso restart` after this file is modified.

imports:
  - "../../private/espanso/match/private.yml"

matches:
  - triggers: ["comitted", "comited", "commited"]
    replace: "committed"

  - trigger: ",hh"
    replace: "happy to help 🎉"

  - trigger: "<details>"
    replace: |
      <details><summary>$|$</summary>

      </details>

  - trigger: ",date"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ",time"
    replace: "{{now}}"
    vars:
      - name: now
        type: date
        params:
          format: "%Y-%m-%dT%H-%M%Z"
