#!/usr/bin/env zsh

# The original idea (and a couple settings) were grabbed from:
# https://github.com/mathiasbynens/dotfiles/blob/master/.osx

if [ -n "$IS_MACOS" ]; then
	# Default finder view: column
	defaults write com.apple.Finder FXPreferredViewStyle clmv

	# Show the ~/Library folder.
	chflags nohidden ~/Library

	brew install --cask rectangle
fi
