#!/usr/bin/env zsh

if [ -n "$IS_MACOS" ]; then
	brew install tmux
	# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
	brew install reattach-to-user-namespace
fi

if [ -n "$IS_LINUX" ]; then
	sudo apt-get install -y tmux
fi

# Install tmux plugin manager
if [ ! -d ~/.tmux/plugins/tpm/ ]; then
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
